---
kind: pipeline
type: docker
name: torrentSearch

platform:
  os: linux
  arch: amd64

steps:
  - name: Build package
    image: python:3.8
    commands:
      - make build

  - name: Run tests
    image: python:3.8
    commands:
      - make install
      - pip install pytest
      - pytest

  - name: Upload coverage report
    image: python:3.8
    commands:
      - pip install -r requirements-dev.txt
      - make install
      - coverage run -m pytest
      - codecov -t $CODECOV_TOKEN
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
